/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ELECTIONS;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Anusha
 */
public class Candidates extends javax.swing.JFrame {

    /**
     * Creates new form Candidates
     */
    public Candidates() {
        initComponents();
        GetElections();
        DisplayCandidates();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CName = new javax.swing.JLabel();
        CandidateNameTb = new javax.swing.JTextField();
        CAge = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        candidatetb = new javax.swing.JTable();
        Cadd = new javax.swing.JButton();
        Cedit = new javax.swing.JButton();
        Cdelete = new javax.swing.JButton();
        Cback = new javax.swing.JButton();
        CAgeTb = new javax.swing.JTextField();
        CGender = new javax.swing.JLabel();
        CandidateGenCb = new javax.swing.JComboBox<>();
        ElectionCb = new javax.swing.JComboBox<>();
        CElections = new javax.swing.JLabel();
        Cpic = new javax.swing.JLabel();
        CandidatePictureLbl = new javax.swing.JLabel();
        BrowseBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1200, 900));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 102, 255));
        jLabel1.setText("                     CAST YOUR VOTE");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 102, 255));
        jLabel2.setText("           Manage Candidates");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(407, 407, 407)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(204, 204, 204)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, Short.MAX_VALUE)
                    .addGap(204, 204, 204)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(jLabel1)
                    .addContainerGap(33, Short.MAX_VALUE)))
        );

        CName.setBackground(new java.awt.Color(255, 255, 255));
        CName.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        CName.setForeground(new java.awt.Color(153, 102, 255));
        CName.setText("Name");

        CandidateNameTb.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        CandidateNameTb.setForeground(new java.awt.Color(102, 102, 255));
        CandidateNameTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CandidateNameTbActionPerformed(evt);
            }
        });

        CAge.setBackground(new java.awt.Color(255, 255, 255));
        CAge.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        CAge.setForeground(new java.awt.Color(153, 102, 255));
        CAge.setText("Age");

        candidatetb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Age", "Gender", "Photo", "Election"
            }
        ));
        candidatetb.setRowHeight(25);
        candidatetb.setSelectionBackground(new java.awt.Color(102, 102, 255));
        candidatetb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                candidatetbMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(candidatetb);

        Cadd.setBackground(new java.awt.Color(255, 255, 255));
        Cadd.setFont(new java.awt.Font("Calibri", 3, 20)); // NOI18N
        Cadd.setForeground(new java.awt.Color(153, 102, 255));
        Cadd.setText("Add");
        Cadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaddActionPerformed(evt);
            }
        });

        Cedit.setBackground(new java.awt.Color(255, 255, 255));
        Cedit.setFont(new java.awt.Font("Calibri", 3, 20)); // NOI18N
        Cedit.setForeground(new java.awt.Color(153, 102, 255));
        Cedit.setText("Edit");
        Cedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CeditActionPerformed(evt);
            }
        });

        Cdelete.setBackground(new java.awt.Color(255, 255, 255));
        Cdelete.setFont(new java.awt.Font("Calibri", 3, 20)); // NOI18N
        Cdelete.setForeground(new java.awt.Color(153, 102, 255));
        Cdelete.setText("Delete");
        Cdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CdeleteActionPerformed(evt);
            }
        });

        Cback.setBackground(new java.awt.Color(255, 255, 255));
        Cback.setFont(new java.awt.Font("Calibri", 3, 20)); // NOI18N
        Cback.setForeground(new java.awt.Color(153, 102, 255));
        Cback.setText("Back");
        Cback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbackActionPerformed(evt);
            }
        });

        CAgeTb.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        CAgeTb.setForeground(new java.awt.Color(102, 102, 255));
        CAgeTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAgeTbActionPerformed(evt);
            }
        });

        CGender.setBackground(new java.awt.Color(255, 255, 255));
        CGender.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        CGender.setForeground(new java.awt.Color(153, 102, 255));
        CGender.setText("Gender");

        CandidateGenCb.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        CandidateGenCb.setForeground(new java.awt.Color(153, 102, 255));
        CandidateGenCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", " ", " " }));

        ElectionCb.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        ElectionCb.setForeground(new java.awt.Color(153, 102, 255));
        ElectionCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElectionCbActionPerformed(evt);
            }
        });

        CElections.setBackground(new java.awt.Color(255, 255, 255));
        CElections.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        CElections.setForeground(new java.awt.Color(153, 102, 255));
        CElections.setText("Elections");

        Cpic.setBackground(new java.awt.Color(255, 255, 255));
        Cpic.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        Cpic.setForeground(new java.awt.Color(153, 102, 255));
        Cpic.setText("Photo");

        CandidatePictureLbl.setBackground(new java.awt.Color(255, 255, 255));
        CandidatePictureLbl.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        CandidatePictureLbl.setForeground(new java.awt.Color(153, 102, 255));
        CandidatePictureLbl.setText("pic");

        BrowseBtn.setBackground(new java.awt.Color(255, 255, 255));
        BrowseBtn.setFont(new java.awt.Font("Calibri", 3, 20)); // NOI18N
        BrowseBtn.setForeground(new java.awt.Color(153, 102, 255));
        BrowseBtn.setText("Browse");
        BrowseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Cadd)
                .addGap(18, 18, 18)
                .addComponent(Cedit)
                .addGap(36, 36, 36)
                .addComponent(Cdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(CElections, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ElectionCb, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 526, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BrowseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(CandidatePictureLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(136, 136, 136))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(CandidateNameTb, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(CName, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CAge, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(CAgeTb))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CandidateGenCb, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CGender, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(107, 107, 107)
                        .addComponent(Cpic, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(Cback, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CAge, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CGender, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CandidateNameTb, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CAgeTb, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CandidateGenCb, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Cpic, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(CElections, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ElectionCb, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(CandidatePictureLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addComponent(BrowseBtn)
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cadd)
                            .addComponent(Cedit)
                            .addComponent(Cdelete))
                        .addGap(26, 26, 26)))
                .addComponent(Cback)
                .addGap(243, 243, 243))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private static int Key=-1;
    Connection myCon = null;
     PreparedStatement pst = null;
     ResultSet Rs = null;
     Statement St = null;
       private void GetElections()
       {
           try {
               myCon = DriverManager.getConnection("jdbc:mysql://localhost:3306/electiondb", "root", "nush2830");  
               St = myCon.createStatement();
               String Query = "select * from electiontb";
               Rs = St.executeQuery(Query);
               while(Rs.next())
               {
                   String ElectId = Rs.getString("Eid");
                   ElectionCb.addItem(ElectId);
               } 
           } catch (Exception e){
                       
                       }
               
           }
         
    
    private void CandidateNameTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CandidateNameTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CandidateNameTbActionPerformed
    public void DisplayCandidates()
       {
            try {
           myCon = DriverManager.getConnection("jdbc:mysql://localhost:3306/electiondb", "root", "nush2830"); 
           St = myCon.createStatement();
           Rs = St.executeQuery("Select * from candidatetb");
           candidatetb.setModel(DbUtils.resultSetToTableModel(Rs));
}catch(SQLException e){
   
}
       }
    int CId;
    Statement St1 = null;
    ResultSet Rs1 = null;
    private void CandCount()
     {
       try {
         St1 = myCon.createStatement();
         Rs1 = St1.executeQuery("select MAx(Cid) from candidatetb");
         Rs1.next();
         CId = Rs1.getInt(1)+1;
            } catch(Exception Ex)
              {
                System.out.print(Ex);
              }
     }
    private void CaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaddActionPerformed
        if(CAgeTb.getText().isEmpty() || CandidateNameTb.getText().isEmpty() || ElectionCb.getSelectedIndex()==-1 || CandidateGenCb.getSelectedIndex()==-1)
        {
           JOptionPane.showMessageDialog(this, "Missing Information");
        } else 
        {
           
          try{
          CandCount();
            myCon = DriverManager.getConnection("jdbc:mysql://localhost:3306/electiondb", "root", "nush2830"); 
            PreparedStatement Add = myCon.prepareStatement("insert into candidatetb values(?,?,?,?,?,?)");
            InputStream img = new FileInputStream(imgpath);
            Add.setInt(1,CId);
            Add.setString(2,CandidateNameTb.getText());
            Add.setInt(3,Integer.valueOf(CAgeTb.getText()));
            Add.setString(4, CandidateGenCb.getSelectedItem().toString());
            Add.setBlob(5,img);
            Add.setInt(6, Integer.valueOf(ElectionCb.getSelectedItem().toString())); //photo bahut bada hai toh nahi jaraha accha dusra try krti
            int row = Add.executeUpdate();
            JOptionPane.showMessageDialog(this, "Candidate Registered");
            myCon.close();
            DisplayCandidates();
             } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex);
                                       } catch (FileNotFoundException ex) {
                Logger.getLogger(Candidates.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_CaddActionPerformed

    private void CeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CeditActionPerformed
         if(Key == -1 || CandidateNameTb.getText().isEmpty() || CAgeTb.getText().isEmpty() || ElectionCb.getSelectedIndex()==-1 || CandidateGenCb.getSelectedIndex()==-1  )
         
       {
           JOptionPane.showMessageDialog(this, "Missing Information");
       } else if(imgpath != null ) 
          {
          try {      ///gussa kaha hau boo boo bas bol raha ab kaunsa hai? admin ka add button
              InputStream img = new FileInputStream(imgpath);// yeh kya karta vo img ke liye
              myCon = DriverManager.getConnection("jdbc:mysql://localhost:3306/electiondb", "root", "nush2830");  
              String Query = "Update candidatetb set Cname=?,Cage=?,Cgender=?,Cphoto=?,Celect=? where Cid=?";
              
             PreparedStatement UpdateQuery = myCon.prepareStatement(Query);
             UpdateQuery.setString(1, CandidateNameTb.getText());
             UpdateQuery.setInt(2, Integer.valueOf(CAgeTb.getText()));
             UpdateQuery.setString(3, CandidateGenCb.getSelectedItem().toString());
             UpdateQuery.setBlob(4, img); 
             UpdateQuery.setString(5, ElectionCb.getSelectedItem().toString());
             UpdateQuery.setInt(6, Key);
             UpdateQuery.executeUpdate();
              //UpdateQuery.executeUpdate(Query);
              JOptionPane.showMessageDialog(this, "Candidate Updated Succesfully");
              DisplayCandidates();
              } catch (Exception e){
               JOptionPane.showMessageDialog(this, e);
           }

          }
    }//GEN-LAST:event_CeditActionPerformed

    private void CdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CdeleteActionPerformed
         if(Key == -1 )
       {
           JOptionPane.showMessageDialog(this, "Select The Candidate To Be Deleted");
       } else 
           {
           try {
              myCon = DriverManager.getConnection("jdbc:mysql://localhost:3306/electiondb", "root", "nush2830");  
              String Query = "Delete from candidatetb where Cid ="+Key;
              Statement Del = myCon.createStatement();
              Del.executeUpdate(Query);
              JOptionPane.showMessageDialog(this, "Candidate Deleted Succesfully");
              DisplayCandidates();
           } catch (Exception e)
           {
                JOptionPane.showMessageDialog(this, e);
           } 
           }
         
    }//GEN-LAST:event_CdeleteActionPerformed

    private ImageIcon ResizePhoto(String ImagePath, byte[] pic) {
          ImageIcon MyImage = null;
          if(ImagePath != null)
        {
          MyImage = new ImageIcon(ImagePath);
        } else{
             MyImage = new ImageIcon(pic);
              }
        Image img =MyImage.getImage();
        Image newImg = img.getScaledInstance(CandidatePictureLbl.getWidth(), CandidatePictureLbl.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
      }
         String imgpath = null;
    private void BrowseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseBtnActionPerformed
        // fetching candidate picture
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images","jpg","gif","png");
        chooser.addChoosableFileFilter(filter);
        int result= chooser.showSaveDialog(this);
        if(result == JFileChooser.APPROVE_OPTION)
        {
           File selectedFile = chooser.getSelectedFile();
           String path = selectedFile.getAbsolutePath();
           CandidatePictureLbl.setIcon(ResizePhoto(path,null));
           imgpath = path;
        }
    }//GEN-LAST:event_BrowseBtnActionPerformed
    private void FetchPhoto()
      {
        String Query = "select Cphoto from candidatetb where Cid="+Key;
        Statement St;
        ResultSet Rs;
          try { 
        myCon = DriverManager.getConnection("jdbc:mysql://localhost:3306/electiondb", "root", "nush2830"); 
        St = myCon.createStatement();
        Rs = St.executeQuery(Query);
         
         CandidatePictureLbl.setIcon(ResizePhoto(null,Rs.getBytes("Cphoto")));
         
              } catch (SQLException ex){

              }
      }
   
    private void candidatetbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_candidatetbMouseClicked
      DefaultTableModel model = (DefaultTableModel)candidatetb.getModel();  
      int MyIndex = candidatetb.getSelectedRow();
       Key = Integer.valueOf(model.getValueAt(MyIndex, 0).toString());
       CandidateNameTb.setText(model.getValueAt(MyIndex, 1).toString());
       CAgeTb.setText(model.getValueAt(MyIndex, 2).toString());
       CandidateGenCb.setSelectedItem(model.getValueAt(MyIndex, 3).toString());
       CandidateGenCb.setSelectedItem(model.getValueAt(MyIndex, 5).toString());//run kar
       FetchPhoto();
       DisplayCandidates();
    }//GEN-LAST:event_candidatetbMouseClicked

    private void CbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbackActionPerformed
        new MainMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CbackActionPerformed

    private void CAgeTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAgeTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CAgeTbActionPerformed

    private void ElectionCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElectionCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ElectionCbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Candidates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Candidates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Candidates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Candidates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Candidates().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BrowseBtn;
    private javax.swing.JLabel CAge;
    private javax.swing.JTextField CAgeTb;
    private javax.swing.JLabel CElections;
    private javax.swing.JLabel CGender;
    private javax.swing.JLabel CName;
    private javax.swing.JButton Cadd;
    private javax.swing.JComboBox<String> CandidateGenCb;
    private javax.swing.JTextField CandidateNameTb;
    private javax.swing.JLabel CandidatePictureLbl;
    private javax.swing.JButton Cback;
    private javax.swing.JButton Cdelete;
    private javax.swing.JButton Cedit;
    private javax.swing.JLabel Cpic;
    private javax.swing.JComboBox<String> ElectionCb;
    private javax.swing.JTable candidatetb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables



   

    
    
        
    
}
