/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ELECTIONS;

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Anusha
 */
public class welcome extends javax.swing.JFrame {

    /**
     * Creates new form welcome
     */
    public welcome() {
        initComponents();
        DisplayCandidates();
        bravoLbl.setVisible(false);
    }
    int VotingId;
    public welcome(int VotingId)
    {
        initComponents();
        DisplayCandidates();
        bravoLbl.setVisible(false);
        VotingId = VoteId;
        //JOptionPane.showMessageDialog(this,"VotingId");
    }
    Connection myCon = null;
     PreparedStatement pst = null;
     ResultSet Rs = null;
     Statement St = null;
public void DisplayCandidates()
       {
            try {
           myCon = DriverManager.getConnection("jdbc:mysql://localhost:3306/electiondb", "root", "nush2830"); 
           St = myCon.createStatement();
           Rs = St.executeQuery("Select * from candidatetb");
           CandidatesTable.setModel(DbUtils.resultSetToTableModel(Rs));
}catch(SQLException e){
   System.out.print(e);
}
       }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CandidatesTable = new javax.swing.JTable();
        backk = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CandidatePictureLbl = new javax.swing.JLabel();
        votebtn = new javax.swing.JButton();
        CnameLbl = new javax.swing.JLabel();
        bravoLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(153, 102, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Calibri", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 102, 255));
        jLabel1.setText("                                       CAST YOUR VOTE                               ");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 102, 255));
        jLabel2.setText("     YOUR VOTE! YOUR VOICE!");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 942, Short.MAX_VALUE)
                .addGap(312, 312, 312))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(390, 390, 390)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CandidatesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Cid", "CName", "CAge", "CGen", "Cphoto", "CElect"
            }
        ));
        CandidatesTable.setRowHeight(25);
        CandidatesTable.setSelectionBackground(new java.awt.Color(153, 153, 255));
        CandidatesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CandidatesTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(CandidatesTable);

        backk.setBackground(new java.awt.Color(255, 255, 255));
        backk.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        backk.setForeground(new java.awt.Color(153, 102, 255));
        backk.setText("Back");
        backk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backkActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 102, 255));
        jLabel6.setText("Candidates list");

        jLabel7.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 102, 255));
        jLabel7.setText(" Your Candidate");

        CandidatePictureLbl.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        CandidatePictureLbl.setForeground(new java.awt.Color(153, 102, 255));
        CandidatePictureLbl.setText("pic");

        votebtn.setBackground(new java.awt.Color(255, 255, 255));
        votebtn.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        votebtn.setForeground(new java.awt.Color(153, 102, 255));
        votebtn.setText("VOTE!");
        votebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                votebtnActionPerformed(evt);
            }
        });

        CnameLbl.setBackground(new java.awt.Color(255, 255, 255));
        CnameLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        CnameLbl.setForeground(new java.awt.Color(153, 102, 255));
        CnameLbl.setText("Name:");

        bravoLbl.setFont(new java.awt.Font("Calibri", 1, 28)); // NOI18N
        bravoLbl.setForeground(new java.awt.Color(0, 204, 51));
        bravoLbl.setText("VOTE COUNTED!!");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1075, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CnameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149)
                        .addComponent(votebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(bravoLbl))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(CandidatePictureLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(182, 182, 182)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backk, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(291, 291, 291))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CandidatePictureLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CnameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(votebtn)
                            .addComponent(bravoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backk)
                .addGap(93, 93, 93))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backkActionPerformed
        new login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backkActionPerformed
int VoteId;
Statement St1;
    
    ResultSet Rs1 = null;
    private void VCount()
    {
        try{
            St1 = myCon.createStatement();
            Rs1 = St1.executeQuery("select MAx(VoteId) from votestb");
            Rs1.next();
            VoteId =Rs1.getInt(1)+ 1;
        }catch (SQLException Ex)
        {
            
        }
    }
    int VNumber;
    private void VCheck()
    {
        try{
            St1 = myCon.createStatement();
            Rs1=St1.executeQuery("select Count * from votestb "+" where VoteId="+VotingId+" and ElectId="+ElectId);
            VNumber = Rs1.getInt(1);
            Rs1.next();
            //int j = Rs1.getInt(1);
            //Rs1=St1.executeQuery();
        
            if(Rs1.next())
             {
                 VNumber = 1;
             }else
             {
                 VNumber = 0;
             }
        }catch (SQLException Ex) 
        {
         JOptionPane.showMessageDialog(this,Ex);
        }
    }
    private void votebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_votebtnActionPerformed
        VCheck();
        if(Key == -1);
  {
        JOptionPane.showMessageDialog(this,"Select Your Candidate");
  }if(VNumber > 0)
          {
          JOptionPane.showMessageDialog(this,"You Cannot Vote Twice");
          votebtn.setVisible(false);
          }else
         try {
             VCount();
             myCon = DriverManager.getConnection("jdbc:mysql://localhost:3306/electiondb", "root", "nush2830");
            PreparedStatement Add = myCon.prepareStatement("insert into votestb values(?,?,?,?)");
                Add.setInt(1,VoteId);
                Add.setInt(2, VotingId);
                Add.setInt(3, ElectId);
                Add.setInt(4,Key);
             int row = Add.executeUpdate();
                JOptionPane.showMessageDialog(this,"Vote Counted");
                myCon.close(); 
                bravoLbl.setVisible(true);
                DisplayCandidates();
                //votebtn.setVisible(false);
       
            } catch (Exception ex)
        {
           JOptionPane.showMessageDialog(this, ex);
        }
         
        
            
          /* try { 
               myCon = DriverManager.getConnection("jdbc:mysql://localhost:3306/electiondb", "root", "nush2830");
                PreparedStatement Add = myCon.prepareStatement("insert into electionTb values(?,?,?,?)");
                Add.setInt(1,VoteId);
                Add.setInt(2, VotingId);
                Add.setInt(3, ElectId);
                Add.setInt(4,Key);
                int row = Add.executeUpdate();
                JOptionPane.showMessageDialog(this,"Vote Counted");
                myCon.close(); 
                bravoLbl.setVisible(true);
                DisplayCandidates();
                votebtn.setVisible(false);
            } catch (Exception e){
                JOptionPane.showMessageDialog(this, e);
            }*/
        
    
    }//GEN-LAST:event_votebtnActionPerformed
    private ImageIcon ResizePhoto(String ImagePath, byte[] pic) {
          ImageIcon MyImage = null;
          if(ImagePath != null)
        {
          MyImage = new ImageIcon(ImagePath);
        } else{
             MyImage = new ImageIcon(pic);
              }
        Image img =MyImage.getImage();
        Image newImg = img.getScaledInstance(CandidatePictureLbl.getWidth(), CandidatePictureLbl.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
      } 
    private void FetchPhoto()
      {
        String Query = "select Cphoto from candidatetb where Cid="+Key;
        Statement St;
        ResultSet Rs;
          try { 
        myCon = DriverManager.getConnection("jdbc:mysql://localhost:3306/electiondb", "root", "nush2830"); 
        St = myCon.createStatement();
        Rs = St.executeQuery(Query);
         if(Rs.next())
         {
             CandidatePictureLbl.setIcon(ResizePhoto(null,Rs.getBytes("Cphoto")));
         }
              } catch (SQLException ex){

              }
      }
    int Key = -1;
    int ElectId;
    private void CandidatesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CandidatesTableMouseClicked
       DefaultTableModel model = (DefaultTableModel)CandidatesTable.getModel();  
      int MyIndex = CandidatesTable.getSelectedRow();
       Key = Integer.valueOf(model.getValueAt(MyIndex, 0).toString());
       CnameLbl.setText(model.getValueAt(MyIndex, 1).toString());
       ElectId = Integer.valueOf(model.getValueAt(MyIndex, 5).toString());
       FetchPhoto();
    }//GEN-LAST:event_CandidatesTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CandidatePictureLbl;
    private javax.swing.JTable CandidatesTable;
    private javax.swing.JLabel CnameLbl;
    private javax.swing.JButton backk;
    private javax.swing.JLabel bravoLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton votebtn;
    // End of variables declaration//GEN-END:variables
}
